### ISSUE TITLE
[Bug]: 3.17 is flagged as a Trojan by Windows 11

### ISSUE THREAD

**Issue by Phyrre56** [unrealities/MTGA_Draft_17Lands#10]
### Describe the bug in detail

When trying to install version 3.17 either through the app itself and the update prompt or by downloading from GitHub, unpacking, and installing from the .exe - Windows 11 flags the file as containing a Trojan (Wacatac.B!ml), halts the installation, and deletes the .exe file. 

This very well could be a false positive but it is consistent and prevents installation. 

### Steps to reproduce this bug

Attempt to install version 3.17 in Windows 11 environment 

### Operating System

Windows

### Operating System Version

Windows 11

### Run Type

Windows Executable

**Comment by FiYir** [comment]
I just tried the new executable and I'm also experiencing this. I've seen this happen when the `--clean` argument isn't used with pyinstaller.

**Comment by unrealities** [comment]
Thank you. Unfortunately, I'm away from my Windows machine for the long weekend. I believe I used the command from the README on the latest build, but I may be mistaken.

**Comment by unrealities** [comment]
I updated the 0317 build with the build created from the build workflow code FiYir implemented. I didn't bump the version as I didn't want an old version out there with possibly malicious or perceived malicious code.

**Comment by unrealities** [comment]
This should be handled by the new process in 3.18, and I removed the flagged 3.17 release.

**Comment by Phyrre56** [comment]
Sorry I was out of town, but thank you for addressing this and I was just able to upgrade to 3.18 so the problem is indeed solved.
