### ISSUE TITLE
[Bug]: run fails for no module pynput

### ISSUE THREAD

**Issue by nottooloud** [unrealities/MTGA_Draft_17Lands#21]
### Describe the bug in detail

Mac M1 Sonoma 14.5, Python 3.12, draft 318 and 319 fail with ModuleNotFoundError: No module named 'pynput'. Pip install pynput seemed to work, but app still fails. Likely something I have done wrong, but...

### Steps to reproduce this bug

Install Mac version per Mac instructions. Run it.

### Operating System

macOS

### Operating System Version

MacOS Sonoma 14.5

### Run Type

Python Script

### Python Version

Python 3.12

**Comment by unrealities** [comment]
Can you elaborate on what "app fails" looks like? What is the result of `python main.py`?

**Comment by nottooloud** [comment]
Python runs, app never loads. This is what’s in Terminal.

Last login: Wed Jun 19 20:55:59 on ttys005
cd '/Users/M1MBP/Downloads/MTGA_Draft_17Lands-MTGA_Draft_Tool_V0318/' && '/usr/local/bin/python3'  '/Users/M1MBP/Downloads/MTGA_Draft_17Lands-MTGA_Draft_Tool_V0318/main.py'  && echo Exit status: $? && exit 1
***@***.*** ~ % cd '/Users/M1MBP/Downloads/MTGA_Draft_17Lands-MTGA_Draft_Tool_V0318/' && '/usr/local/bin/python3'  '/Users/M1MBP/Downloads/MTGA_Draft_17Lands-MTGA_Draft_Tool_V0318/main.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/M1MBP/Downloads/MTGA_Draft_17Lands-MTGA_Draft_Tool_V0318/main.py", line 5, in <module>
    from src.overlay import start_overlay
  File "/Users/M1MBP/Downloads/MTGA_Draft_17Lands-MTGA_Draft_Tool_V0318/src/overlay.py", line 14, in <module>
    from pynput.keyboard import Listener, KeyCode
ModuleNotFoundError: No module named 'pynput'
***@***.*** MTGA_Draft_17Lands-MTGA_Draft_Tool_V0318 %

**Comment by nottooloud** [comment]
Does work fine on another M1 Mac, so it’s probably something in my setup.

**Comment by unrealities** [comment]
Yea, it looks like pynput still is not installed correctly.
