### ISSUE TITLE
[Bug]: Error in downloading dataset

### ISSUE THREAD

**Issue by haldobaglio** [unrealities/MTGA_Draft_17Lands#43]
### Describe the bug in detail

Upon attempting to download the dataset for any expansion, the following error message is displayed: "Download failed: couldn't retrieve card data."
The download process is terminated immediately.
![error message mtgadrafttool](https://github.com/user-attachments/assets/efd160fc-33ed-4fa4-b11b-2ec8030651bf)

Thank you for your support.

### Steps to reproduce this bug

1. Open MTGA Draft Tool
2. in Data -> Download dataset
3. Download (any expansion)

### Operating System

Windows

### Operating System Version

Windows 10 Home

### Run Type

Windows Executable

### Debug Log Details

<07/28/2024 16:23:59> - INFO - Platform: win32
<07/28/2024 16:23:59> - INFO - Scale Factor 1.0
<07/28/2024 16:23:59> - INFO - Arena Log: Searching File Path C:/Users\matte\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log
<07/28/2024 16:23:59> - INFO - Card Data Location: C:/Program Files/Wizards of the Coast/MTGA/MTGA_Data
<07/28/2024 16:24:01> - INFO - Event found QuickDraft_OTJ_20240716
<07/28/2024 16:24:01> - INFO - Event found QuickDraft_OTJ_20240716
<07/28/2024 16:24:02> - INFO - Event found Historic_Play
<07/28/2024 16:24:05> - INFO - Arena Player Log Location: C:/Users\matte\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log
<07/28/2024 16:24:20> - INFO - Local File Change Detected 129630208, 0
<07/28/2024 16:24:20> - INFO - Local Database Data: Searching File Path C:/Program Files/Wizards of the Coast/MTGA/MTGA_Data\Downloads\Raw\Raw_CardDatabase_4d93d5a0250b2c5176c96558da3d1ee7.mtga
<07/28/2024 16:24:20> - ERROR - file_extractor._retrieve_local_database - database disk image is malformed
<07/28/2024 16:24:20> - ERROR - file_extractor._retrieve_local_arena_data - Couldn't Collect Local Card Data

### Possible Solution (optional)

Uninstalling and re-installing MTG Arena solves the problem

**Comment by FiYir** [comment]
Could you share the debug log details? There isn't much we can do without this info.

If you’re concerned about privacy, you can edit the log like riQQ did in issue #42, where they swapped their username with `<user>`.

**Comment by haldobaglio** [comment]
Sure. Here it is:

<07/28/2024 16:23:59> - INFO - Platform: win32
<07/28/2024 16:23:59> - INFO - Scale Factor 1.0
<07/28/2024 16:23:59> - INFO - Arena Log: Searching File Path C:/Users\matte\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log
<07/28/2024 16:23:59> - INFO - Card Data Location: C:/Program Files/Wizards of the Coast/MTGA/MTGA_Data
<07/28/2024 16:24:01> - INFO - Event found QuickDraft_OTJ_20240716
<07/28/2024 16:24:01> - INFO - Event found QuickDraft_OTJ_20240716
<07/28/2024 16:24:02> - INFO - Event found Historic_Play
<07/28/2024 16:24:05> - INFO - Arena Player Log Location: C:/Users\matte\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log
<07/28/2024 16:24:20> - INFO - Local File Change Detected 129630208, 0
<07/28/2024 16:24:20> - INFO - Local Database Data: Searching File Path C:/Program Files/Wizards of the Coast/MTGA/MTGA_Data\Downloads\Raw\Raw_CardDatabase_4d93d5a0250b2c5176c96558da3d1ee7.mtga
<07/28/2024 16:24:20> - ERROR - file_extractor._retrieve_local_database - database disk image is malformed
<07/28/2024 16:24:20> - ERROR - file_extractor._retrieve_local_arena_data - Couldn't Collect Local Card Data

Thank you.

**Comment by haldobaglio** [comment]
Uninstalling & Re-installing Arena solves the problem.
I edited the first post.
Thank you
