### ISSUE TITLE
[Bug]: version 3.26 - 3.21 detected as malware by antivirus software

### ISSUE THREAD

**Issue by RealLifeTokyoGirl** [unrealities/MTGA_Draft_17Lands#49]
### Describe the bug in detail

Each version of the application from 3.21 onwards are detected as malware by MalwareBytes and quarantined. However, the issue is not present with version 3.20 and previous, which continue to work as expected. 

### Steps to reproduce this bug

1. Run version 3.21 or later with MalwareBytes installed and realtime protection on, OR run a malware scan with v3.21 or later installed.
2. The application will immediately be killed and quarantined, whitelisting does not help.

### Operating System

Windows

### Operating System Version

Windows 10 Pro x64

### Run Type

Windows Executable

### Possible Solution (optional)

Downgrade to v3.20. Likely a change introduced in v3.21 is to blame.

**Comment by FiYir** [comment]
@RealLifeTokyoGirl, the code is open source and the executable is built using a [GitHub Action](https://github.com/unrealities/MTGA_Draft_17Lands/actions/runs/10134149031), so you can review the project yourself and confirm that no malicious code has been added.

If you encounter a detection issue, please report it to Malwarebytes on their [File Detections forum](https://forums.malwarebytes.com/forum/42-file-detections/) for review.

Thanks.
