### ISSUE TITLE
[Bug]: Traditional Draft not displaying results

### ISSUE THREAD

**Issue by unrealities** [unrealities/MTGA_Draft_17Lands#53]
### Describe the bug in detail

I started a Duskmourn Traditional Draft, and the log was being populated, but the application was not showing results during any pick.

### Steps to reproduce this bug

1. Open Application
2. Start Traditional DSK Draft

### Operating System

Windows

### Operating System Version

Mac OSX 14.6.1

### Run Type

Windows Executable

### Python Version

Python 3.12.3

### Debug Log Details

Logs never showed a new event detected...

```
MTGA_Draft_17Lands % python3 main.py
<10/17/2024 15:04:39> - INFO - Platform: darwin
<10/17/2024 15:04:39> - INFO - Scale Factor 1.0
<10/17/2024 15:04:39> - INFO - Arena Log: Searching File Path /Users/name/Library/Logs/Wizards Of The Coast/MTGA/Player.log
<10/17/2024 15:04:39> - INFO - Card Data Location: 
<10/17/2024 15:04:41> - INFO - Arena Player Log Location: /Users/name/Library/Logs/Wizards Of The Coast/MTGA/Player.log
```

### Possible Solution (optional)

We need to review the log file to see what may have changed as an update was released.

[TradDraft_DSK_10172024.log](https://github.com/user-attachments/files/17422834/TradDraft_DSK_10172024.log)

**Comment by unrealities** [comment]
I'm not seeing an `Event_Join`

The business events I see at the start of the draft:
```log
[UnityCrossThreadLogger]==> LogBusinessEvents
{"id":"f26a22c1-4cd9-4234-b1e4-c6ddb7043a37","request":"{\"toSceneName\":\"Draft\",\"fromSceneName\":\"TableDraftQueue\",\"initiator\":\"System\",\"context\":\"HumanDraft\",\"duration\":\"00:01:08.8498420\",\"transitionTimeSeconds\":\"00:00:01.1280250\",\"EventType\":33,\"EventTime\":\"2024-10-17T20:05:41.876642Z\"}"}
```

P1P1:
```log
[UnityCrossThreadLogger]==> Event_PlayerDraftMakePick
{"id":"c254678f-6450-4fb2-86ac-2badaf1e3837","request":"{\"DraftId\":\"698675c7-976a-4687-9ca9-cf209ce49f61\",\"GrpId\":92104,\"Pack\":1,\"Pick\":1}"}
```

The first instance of a DraftId:
```log
[UnityCrossThreadLogger]==> Event_PlayerDraftMakePick
{"id":"c254678f-6450-4fb2-86ac-2badaf1e3837","request":"{\"DraftId\":\"698675c7-976a-4687-9ca9-cf209ce49f61\",\"GrpId\":92104,\"Pack\":1,\"Pick\":1}"}
```

**Comment by FiYir** [comment]
It worked for me. 
[DraftLog_DSK_TradDraft_d0d65068-aafe-420a-a3fe-9373cb408b87.log](https://github.com/user-attachments/files/17441055/DraftLog_DSK_TradDraft_d0d65068-aafe-420a-a3fe-9373cb408b87.log)

Did you draft while they were [updating the client](https://magicthegatheringarena.statuspage.io/)?

**Comment by unrealities** [comment]
> It worked for me. [DraftLog_DSK_TradDraft_d0d65068-aafe-420a-a3fe-9373cb408b87.log](https://github.com/user-attachments/files/17441055/DraftLog_DSK_TradDraft_d0d65068-aafe-420a-a3fe-9373cb408b87.log)
> 
> Did you draft while they were [updating the client](https://magicthegatheringarena.statuspage.io/)?

Thank you for responding. It was in that window and I was hoping it was just a fluke, but I wanted to get it documented just in case.
